# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Placeholder-Named
version:      0.06
version_from: lib/DBIx/Placeholder/Named.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    SQL::Tokenizer:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
