--- #YAML:1.0
name:                DBIx-Placeholder-Named
version:             0.07
abstract:            ~
license:             ~
author:              
    - Igor Sutton <igor.sutton@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::SQLite:                   0
    DBI:                           0
    SQL::Tokenizer:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
